### PR TITLE
promtail ansible role improvements

### PR DESCRIPTION
**Pull request by jpescalona**
I found the following improvements interesting for this role:
1. Make promtail installation dependant to the package manager of the OS
2. Only expose promtail port if firewalld is enabled

### CODE REVIEW

**Comment by voidquark** [comment]
This role also includes an `uninstall.yml` file, which must be aligned correctly with these changes. However, let me explain why I believe it may not make sense:

Which OS are you trying to target with these changes? I am primarily focusing on RHEL-compatible distros, as stated in the README.

Debian or Ubuntu?

**Comment by jpescalona** [comment]
Hi, thanks for the feedback. This not specifically for other operating
systems like debian or Ubuntu, just to add backward compatibility to
systems that still uses yum as package manager. But I see in galaxy it's
only supported for EL 7 and 8.

Regarding the changes related to the firewall, do you agree?

I will remove the change to avoid using ansible.builtin.package.

Sorry if there was any misunderstanding.

**Comment by voidquark** [comment]
The meta file lists support for EL 8 and 9. EL 7 is already at EOL (full support has ended), and I have no plans to support EL 7. Regarding firewall changes, I agree that we should implement them. I intentionally set it up this way because I believe the firewall should be mandatory and not disabled in any environment. Please also update the uninstall play so that it only executes when firewalld is active, ensuring it aligns with the deploy changes.

**Comment by jpescalona** [comment]
I agree that firewall should be mandatory, but there certain cases it is disabled for various reasons.

I've updated the PR with the fw change you've suggested in uninstall.

**Comment by voidquark** [comment]
In this role, all internally registered variables should have __ preceding them. Therefore, it should be __firewalld_service_state. Please update also this.

**Comment by voidquark** [comment]
Do you plan to apply this, or should I close the PR?

**Comment by voidquark** [comment]
Already implemented.

**Pull request closed without merging**
